FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY engine/js/package*.json ./

# Install any dependencies
RUN npm install

# Copy the rest of the code
COPY engine/js/ .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD [ "npm", "start" ]